name = "co-up-game-server"
main = "src/game-room.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "GameRoom"

[[migrations]]
tag = "v1"
new_classes = ["GameRoom"]
